

FROM ubuntu:22.04
LABEL maintainer "Kari Salokas kari.salokas@helsinki.fi"

ENV DEBIAN_FRONTEND noninteractive
ENV LC_CTYPE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV R_BASE_VERSION 3.6.1

# First steps
USER root

# Install and setup R and other software
# Updates and packages
RUN apt-get update && \
    apt-get -yq dist-upgrade && \
    apt-get install -yq \
    software-properties-common dirmngr wget xz-utils cron
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

RUN apt-get install -yq apt-utils software-properties-common locales \
    git python3 python3-pip nodejs npm  \
    dos2unix ca-certificates nano postgresql \
    littler gnupg \
    r-cran-littler \
    r-base \
    r-base-dev \
    r-recommended \
    redis psmisc
RUN wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc
RUN echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main" > /etc/apt/sources.list.d/cranapt.list
RUN apt-get update -qq
RUN npm install -g configurable-http-proxy
RUN apt-get -y install libcurl4-gnutls-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

RUN echo "Package: *" > /etc/apt/preferences.d/99cranapt
RUN echo "Pin: release o=CRAN-Apt Project" >> /etc/apt/preferences.d/99cranapt
RUN echo "Pin: release l=CRAN-Apt Packages" >> /etc/apt/preferences.d/99cranapt
RUN echo "Pin-Priority: 700"  >> /etc/apt/preferences.d/99cranapt

## Then install bspm (as root) and enable it, and enable a speed optimization
RUN Rscript -e 'install.packages("bspm")'
RUN RHOME=$(R RHOME)
RUN echo "suppressMessages(bspm::enable())" >> ${RHOME}/etc/Rprofile.site
RUN echo "options(bspm.version.check=FALSE)" >> ${RHOME}/etc/Rprofile.site


# User management not needed for now
#RUN adduser --quiet --disabled-password --shell /bin/bash --gecos "Kari" kamms && \
#    echo "kamms:kamms" | chpasswd
WORKDIR /
COPY app /proteogyver
COPY app/resources /proteogyver/resources
# Python installs
WORKDIR /proteogyver/resources
RUN pip3 install --upgrade pip
RUN pip3 install setuptools
RUN pip3 install --ignore-installed -r requirements.txt
RUN pip3 install jupyter jupyterlab jupyterhub pandas jupyter-dash gunicorn

# JupyterHub
# R things
#RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site
RUN echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))' >> /etc/R/Rprofile.site
COPY docker_entrypoint.sh /
COPY app/update.sh /update.sh
WORKDIR /
WORKDIR /proteogyver/resources
#Needed for R
#/usr/local/lib/R/etc/Rprofile.site
RUN Rscript R_requirements.R
RUN Rscript R_requirements2.R
RUN Rscript R_requirements3.R
RUN Rscript R_requirements4.R

# Finished.
ENTRYPOINT ["/bin/bash", "/docker_entrypoint.sh"]
