

FROM pgbase:pgbase
LABEL maintainer "Kari Salokas kari.salokas@helsinki.fi"

# First steps
USER root
WORKDIR /
RUN mkdir /proteogyver
COPY docker_entrypoint.sh /
COPY app/update.sh /update.sh
COPY app /proteogyver
COPY app/Utilities/cron_maintenance_jobs /etc/cron.d/cron_maintenance_jobs
RUN chmod 0644 /etc/cron.d/cron_maintenance_jobs
RUN crontab /etc/cron.d/cron_maintenance_jobs
RUN touch /var/log/cron.log

RUN adduser --quiet --disabled-password --shell /bin/bash --gecos "Kari" kamms && \
    echo "kamms:kamms" | chpasswd

# Make SAINT executable
WORKDIR /proteogyver/external/SAINTexpress
RUN chmod 777 SAINTexpress-spc
RUN chmod 777 SAINTexpress-int

WORKDIR /

# Unpack database
WORKDIR /proteogyver/data
RUN unxz proteogyver.db.xz
RUN mkdir -p /etc/supervisor/conf.d
RUN cp /proteogyver/other_commands/celery.conf /etc/supervisor/conf.d/celery.conf
# Python installs
WORKDIR /proteogyver
RUN sed -i 's\"/mnt", "c", "DATA", "PG cache"\"/proteogyver", "cache"\g' parameters.json  
RUN mkdir /proteogyver/cache
WORKDIR /proteogyver/resources
RUN pip3 install --upgrade pip
RUN pip3 install --ignore-installed -r requirements.txt

# Expose ports (dash)
EXPOSE 8050

# Finished.
ENTRYPOINT ["/bin/bash", "/docker_entrypoint_testing.sh"]
