

FROM ubuntu:22.04
LABEL maintainer "Kari Salokas kari.salokas@helsinki.fi"

ENV DEBIAN_FRONTEND noninteractive
ENV LC_CTYPE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

# First steps
USER root
WORKDIR /
RUN mkdir /proteogyver
#COPY docker_entrypoint.sh /
#COPY app/update.sh /update.sh
#COPY app /proteogyver
# update indices
RUN apt update -qq

# install R
RUN apt install --no-install-recommends software-properties-common dirmngr
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
RUN add-apt-repository ppa:c2d4u.team/c2d4u4.0+
RUN apt update -qq
RUN apt install --no-install-recommends r-base r-cran-tidyvers


# Expose ports (jupyterHub. dash)
EXPOSE 8050

# Finished.
ENTRYPOINT ["/bin/bash", "/docker_entrypoint.sh"]