

FROM ubuntu:22.04
LABEL maintainer "Kari Salokas kari.salokas@helsinki.fi"

ENV DEBIAN_FRONTEND noninteractive
ENV LC_CTYPE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

# First steps
USER root
WORKDIR /
RUN mkdir /proteogyver
COPY docker_entrypoint.sh /
COPY app/update.sh /update.sh
COPY app /proteogyver

# Install and setup R and other software
# Updates and packages
RUN apt-get update && \
    apt-get -yq dist-upgrade && \
    apt-get install -yq \
    software-properties-common dirmngr wget
RUN apt-get install -yq apt-utils software-properties-common locales \
    git python3 python3-pip nodejs npm  \
    dos2unix ca-certificates nano postgresql \
    littler 


# Python installs
WORKDIR /proteogyver/resources
RUN pip3 install --upgrade pip
RUN pip3 install setuptools
RUN pip3 install -r requirements.txt
RUN pip3 install jupyter jupyterlab jupyterhub pandas jupyter-dash gunicorn
RUN npm install -g configurable-http-proxy

# User management
RUN adduser --quiet --disabled-password --shell /bin/bash --gecos "Kari" kamms && \
    echo "kamms:kamms" | chpasswd

# Make SAINT executable
WORKDIR /proteogyver/external/SAINTexpress
RUN chmod 777 SAINTexpress-spc
RUN chmod 777 SAINTexpress-int
WORKDIR /
# JupyterHub
RUN mkdir /etc/jupyterhub
COPY jupyterhub.py /etc/jupyterhub/

# Put additional data where it should be
COPY additional/data.tar /proteogyver/data.tar
COPY additional/external.tar /proteogyver/external.tar
WORKDIR /proteogyver
RUN tar xf data.tar
RUN tar xf external.tar


# Expose ports (jupyterHub. dash)
EXPOSE 8090 8050

# Finished.
ENTRYPOINT ["/bin/bash", "/docker_entrypoint.sh"]