readRenviron("/etc/default/locale")
LANG <- Sys.getenv("LANG")
if(nchar(LANG))
   Sys.setlocale("LC_ALL", LANG)
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::pkg_install(c("BiocManager", "devtools"))
pak::pkg_install(c("Bioc::DEP", "Bioc::SummarizedExperiment", "Bioc::MSnbase", "Bioc::pcaMethods", "Bioc::vsn", "Bioc::impute"))
pak::pkg_install(c("IRkernel", "tidyverse", "flashClust", "proteomicsCV", "samr", "WGCNA", "imputeLCMD"))

library(devtools)
install_github("https://github.com/vdemichev/diann-rpackage")