readRenviron("/etc/default/locale")
LANG <- Sys.getenv("LANG")
if(nchar(LANG))
   Sys.setlocale("LC_ALL", LANG)
install.packages('BiocManager')
BiocManager::install("impute")
BiocManager::install("pcaMethods")
BiocManager::install("vsn")