install.packages(c('BiocManager', 'proteomicsCV', 'vsn', 'IRkernel', 'devtools', 'tidyverse', 'flashClust', 'WGCNA', 'samr'), ncpus=12)
BiocManager::install(c('DEP', 'AnnotationDb', 'GO.db', 'preprocessCore', 'impute'))
IRkernel::installspec(user = FALSE) 
library(devtools)
install_github("https://github.com/vdemichev/diann-rpackage")