services:
  pgyver_production:
    image: pgyver:1.5
    container_name: pgprod15
    ports:
      - 8050:8050
    environment:
      - TZ=Europe/Helsinki
      - MONITOR_RESOURCES=true
      - RESOURCE_LOG_DIR=/proteogyver/data/Server_output/logs/resources
      - RESOURCE_LOG_INTERVAL_SECONDS=5
      - RESOURCE_LOG_KEEP_DAYS=30

    volumes:
      - /data/PG_containers/finaltest/cache:/proteogyver/cache
      - /data/PG_containers/finaltest/db:/proteogyver/data/db
      - /data/PG_containers/finaltest/input:/proteogyver/data/Server_input
      - /data/PG_containers/finaltest/output:/proteogyver/data/Server_output
      # This is required for the updater to share one parameter file with the server.
      - /data/PG_containers/finaltest/conf/parameters.toml:/proteogyver/parameters.toml
    restart: unless-stopped
