

FROM ubuntu:22.04
LABEL maintainer "Kari Salokas kari.salokas@helsinki.fi"
USER root

WORKDIR /
COPY dockerfiles/docker_entrypoint.sh /
COPY utils/resource_monitoring.sh /
COPY app /proteogyver
# Python installs
WORKDIR /proteogyver/resources
RUN pip3 install --upgrade pip
RUN pip3 install setuptools
RUN pip3 install --ignore-installed -r requirements.txt
RUN pip3 install jupyter jupyterlab jupyterhub pandas jupyter-dash gunicorn

# JupyterHub
# R things
RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site
WORKDIR /proteogyver/resources
#Needed for R
#/usr/local/lib/R/etc/Rprofile.site
RUN Rscript R_requirements.R

# Finished.
ENTRYPOINT ["/bin/bash", "/docker_entrypoint.sh"]
