FROM ubuntu:24.04
LABEL maintainer="Kari Salokas kari.salokas@helsinki.fi"
USER root
RUN apt-get update && \
    apt-get -yq dist-upgrade
RUN apt-get install -yq locales

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
# Configure locale to avoid runtime errors
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

ENV LC_CTYPE="en_US.UTF-8"
ENV LC_ALL="en_US.UTF-8"
ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US:en"
ENV R_BASE_VERSION="3.6.1"
ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get install -yq \
    software-properties-common dirmngr wget xz-utils cron
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

RUN apt-get install -yq apt-utils software-properties-common  \
    git python3 python3-pip nodejs npm  \
    dos2unix ca-certificates nano postgresql \
    littler gnupg \
    r-cran-littler \
    r-base \
    r-base-dev \
    r-recommended \
    redis psmisc
RUN wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc
RUN echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main" > /etc/apt/sources.list.d/cranapt.list
RUN apt-get update -qq
RUN npm install -g configurable-http-proxy
RUN apt-get -y install libcurl4-gnutls-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

#COPY app/update.sh /update.sh
WORKDIR /
RUN echo "Package: *" > /etc/apt/preferences.d/99cranapt
RUN echo "Pin: release o=CRAN-Apt Project" >> /etc/apt/preferences.d/99cranapt
RUN echo "Pin: release l=CRAN-Apt Packages" >> /etc/apt/preferences.d/99cranapt
RUN echo "Pin-Priority: 700"  >> /etc/apt/preferences.d/99cranapt

## Then install bspm (as root) and enable it, and enable a speed optimization
RUN Rscript -e 'install.packages("bspm")'
RUN RHOME=$(R RHOME)
RUN echo "suppressMessages(bspm::enable())" >> ${RHOME}/etc/Rprofile.site
RUN echo "options(bspm.version.check=FALSE)" >> ${RHOME}/etc/Rprofile.site
RUN echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))' >> /etc/R/Rprofile.site


WORKDIR /
COPY app /proteogyver
COPY dockerfiles/docker_entrypoint.sh /docker_entrypoint.sh
RUN chmod +x /docker_entrypoint.sh

# Make SAINT executable
WORKDIR /proteogyver/external/SAINTexpress
RUN chmod 777 SAINTexpress-spc
RUN chmod 777 SAINTexpress-int
RUN ln -s /proteogyver/external/SAINTexpress/SAINTexpress-spc /usr/bin/SAINTexpressSpc
RUN ln -s /proteogyver/external/SAINTexpress/SAINTexpress-int /usr/bin/SAINTexpressInt

RUN mkdir -p /proteogyver/data/Server_output
RUN mkdir -p /proteogyver/data/MS_rundata
RUN mkdir -p /proteogyver/data/Server_output/logs
RUN cp /proteogyver/resources/celery.conf /etc/supervisor/conf.d/celery.conf

WORKDIR /proteogyver
RUN sed -i 's\"/home", "kmsaloka", "Documents", "PG_cache"\"/proteogyver", "cache"\g' parameters.toml  
RUN sed -i 's\"Local debug" = true\"Local debug" = false\g' parameters.toml

# This will fix a bug in the 0.6 version of dash_uploader. It's a very crude method, but it works for this application.
#RUN sed -i 's/isinstance/False:#/g' /usr/local/lib/python3.10/dist-packages/dash_uploader/callbacks.py

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    mkdir -p /root/.conda && \
    bash miniconda.sh -b -p /root/miniconda3 && \
    rm -f miniconda.sh
WORKDIR /proteogyver
RUN conda env create -f resources/environment.yml
RUN conda clean -afy
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate proteogyver" >> ~/.bashrc

WORKDIR /proteogyver/resources
#Needed for R
#/usr/local/lib/R/etc/Rprofile.site
RUN Rscript R_requirements.R
RUN Rscript R_requirements2.R
RUN Rscript R_requirements3.R
RUN Rscript R_requirements4.R
RUN Rscript R_requirements5.R
RUN Rscript R_requirements6.R
RUN Rscript R_requirements7.R
RUN Rscript R_requirements8.R
RUN Rscript R_requirements9.R
RUN Rscript R_requirements10.R
RUN Rscript R_requirements11.R
RUN Rscript R_requirements12.R
RUN Rscript R_requirements13.R
RUN Rscript R_requirements14.R

EXPOSE 8090 8050

RUN echo "source activate proteogyver" >> ~/.bashrc
ENV PATH="/opt/conda/envs/proteogyver/bin:${PATH}"

ENTRYPOINT ["/bin/bash", "/docker_entrypoint.sh"]


