services:
  proteogyver:
    image: proteogyver:1.0
    container_name: proteogyver
    ports:
      - 8050:8050
    environment:
      - TZ=Europe/Helsinki
      - MONITOR_RESOURCES=false
      - RESOURCE_LOG_DIR=/proteogyver/data/Server_output/logs/resources
      - RESOURCE_LOG_INTERVAL_SECONDS=5
      - RESOURCE_LOG_KEEP_DAYS=30

    volumes:
      - /data/PG_ext_Data/cache:/proteogyver/cache
      - /data/PG_ext_data/db:/proteogyver/data/db
      - /mnt/MS_rundata:/proteogyver/data/Server_input
      - /mnt/Server_output:/proteogyver/data/Server_output
      # This is required for the updater to share one parameter file with the server.
      - /data/PG_ext_data/conf/parameters.toml:/proteogyver/parameters.toml
    restart: unless-stopped
